### ISSUE TITLE
WordCount: Error thrown on word count when sanitization results in whitespace-only string

### ISSUE THREAD

**Issue by aduth** [WordPress/packages#122]
Related: https://github.com/WordPress/gutenberg/issues/6617

When trying to count words for a string which includes only content which would be removed by the sanitization which occurs prior to matching words (HTML tag / comments / etc removal), `@wordpress/wordcount` throws an error:

```
⇒ node          
> var wordcount = require( '@wordpress/wordcount' );
undefined
> wordcount.count( '<p></p>', 'words' );
TypeError: Cannot read property 'length' of null
    at Object.count (/Users/andrew/Documents/Code/vvv/www/editor/htdocs/wp-content/plugins/gutenberg/node_modules/@wordpress/wordcount/build/index.js:121:50)
```

**Comment by aduth** [comment]
Will do. Thanks @ryanwelcher !

**Comment by ryanwelcher** [comment]
@aduth did you want to add me to the org? I promise I won't merge anything without asking :)

**Comment by aduth** [comment]
I would, but I do not have permission to do so 😄 cc @pento @mtias

**Comment by ryanwelcher** [comment]
@aduth no problem :) I've added a PR that addresses this with #123
