### ISSUE TITLE
didAction() incorrectly returns 0 until it has a function attached

### ISSUE THREAD

**Issue by pento** [WordPress/packages#133]
In Core, `did_action()` returns the number of times a hook has been fired.

In `@wordpress/hooks`, `didAction()` returns the number of times a hook has been fired _after_ a function has been attached to it.

For example, the following test:

```js
const { doAction, addAction, didAction } = require( '@wordpress/hooks' );

function foo() {}

addAction( 'bar', 'foo', foo );

console.log( "We haven't done 'bar' yet", didAction( 'bar' ) );

doAction( 'bar' );

console.log( "Now we have", didAction( 'bar' ) );

console.log( "We haven't done 'baz' yet", didAction( 'baz' ) );

doAction( 'baz' );

console.log( "Now we have", didAction( 'baz' ) );
```

Produces:

```
We haven't done 'bar' yet 0
Now we have 1
We haven't done 'baz' yet 0
Now we have 0
```

However, the same code in PHP:

```php
<?php

include_once( '../wordpress-develop/src/wp-includes/plugin.php' );

function foo() {}

add_action( 'bar', 'foo' );

echo "We haven't done 'bar' yet ", did_action( 'bar' ), "\n";

do_action( 'bar' );

echo "Now we have ", did_action( 'bar' ), "\n";

echo "We haven't done 'baz' yet ", did_action( 'baz' ), "\n";

do_action( 'baz' );

echo "Now we have ", did_action( 'baz' ), "\n";
```

Produces:

```
We haven't done 'bar' yet 0
Now we have 1
We haven't done 'baz' yet 0
Now we have 1
```

**Comment by aduth** [comment]
Related: #78 / #102

**Comment by pento** [comment]
The PHP behaviour is correct.

For example, a common pattern in both Core and plugins is to check `did_action( 'init' )` (or some other similar early action), to determine if WordPress has loaded to the point that particular code can be safely run. To be able to do that, it needs to record every time `do_action()` is called for the filter, not just the times it's called when there's a function attached to it.
