### ISSUE TITLE
Re-work directory structure

### ISSUE THREAD

**Issue by nylen** [WordPress/packages#20]
The current paths in this repo are a bit unwieldy:

```php
~ # cd ~/wp/packages/
~/wp/packages # ls
CONTRIBUTING.md  lerna.json    package.json       packages   scripts
~/wp/packages # cd packages/hooks/src/
~/wp/packages/packages/hooks/src # ls
createAddHook.js
createCurrentHook.js
createDidHook.js
createDoingHook.js
createHasHook.js
createRemoveHook.js
createRunHook.js
hooks.js
index.js
test
```

Proposal to simplify things a bit.  Rename `packages/` to `src/` and get rid of the `src/` directory inside each individual package:

```diff
- packages/hooks/src/*.js
+ src/hooks/*.js
```

**Comment by youknowriad** [comment]
I think we should keep the `src` folder in each individual package, we could imagine more root folders for individual packages ( `docs`, `scripts` ...). Not against renaming the `packages` directory but it seems like the default for all lerna repositories. 

Maybe the problem is the name of the repository :)

**Comment by nylen** [comment]
> I think we should keep the src folder in each individual package, we could imagine more root folders for individual packages ( docs, scripts ...)

These folders should all be global though, otherwise we fail to achieve one of the goals of this repo (a centralized place to build WordPress JS without duplicating a bunch of effort).

I don't necessarily want to reopen the discussion about the repository name. I'd be fine with just removing the `src/` subfolders (and then I would probably name this `~/wp/js` on my computer).

**Comment by gziolo** [comment]
`packages` subfolder is a default pick inherited from Lerna. See https://github.com/lerna/lerna#what-does-a-lerna-repo-look-like:

```
my-lerna-repo/
  package.json
  packages/
    package-1/
      package.json
    package-2/
      package.json
```

Feel free to open PR to change that. I'm fine with following the default choice.
