### ISSUE TITLE
Reintroduce browser build

### ISSUE THREAD

**Issue by aduth** [WordPress/packages#24]
Related: #23
Slack discussion: https://wordpress.slack.com/archives/C5UNMSU4R/p1501594355646576

The browser build was removed in #23 because the generated file was problematic and could not be used in a browser. Specifically, it still included `require` CommonJS statements and implicit dependencies on the Babel runtime.

An independent browser bundle may still be useful to include in the packages distributable for developers who would like to use a module independent of WordPress, and without an npm build process. You can see other libraries which support this installation process via tools like [unpkg](https://unpkg.com/redux@3.7.2/dist/): https://github.com/reactjs/redux#installation

While it's questionable whether this should be a priority, or whether the browser build should occur in a consuming project with npm build process (like Wordpress), it may not be significant effort to reintroduce to [existing build variant configurations](https://github.com/WordPress/packages/blob/fd7fff1/scripts/build.js#L37-L49).

**Comment by ntwb** [comment]
Issue moved to [WordPress/gutenberg #7600](https://github.com/WordPress/gutenberg/issues/7600) via [**ZenHub**](https://www.zenhub.com/)
