### ISSUE TITLE
Possible problem with package.json for @wordpress/dom-ready package distributed on npm

### ISSUE THREAD

**Issue by nerrad** [WordPress/packages#41]
The following is found in `dom-ready/package.json`:

```
"main": "build/index.js",
"module": "build-module/index.js",
```

When I install the package via `npm install @wordpress/dom-ready --save`, the main `index.js` file ends up in `node_modules/@wordpress/dom-ready/src/index.json`.   So that means doing this in my js won't work:

```
import domReady from '@wordpress/dom-ready`;
```

...which results when using webpack to build my js:

```
Module not found: Error: Can't resolve '@wordpress/dom-ready'
```

shouldn't `"main" : "build/index.js"` be distributed as `"main" : "src/index.js"` ?

**Comment by nerrad** [comment]
If I change my import statement to the following it works:

```
import domReady from '@wordpress/dom-ready/src/'
```

**Comment by youknowriad** [comment]
Interesting. I think `main` is correct, it should refer to the ES5 version (the built version) and `module` to an ES5 version with ES6 modules to enable tree shaking. 

I suspect a problem elsewhere, did you try to install it this way `npm install @wordpress/dom-ready@next --save`. if you drop the `next` it will install the "stable" version which in theory we do not have yet but I recall we messed up our first release, might be related?

**Comment by nerrad** [comment]
ya so `npm install @wordpress/dom-ready@next --save` results in the `build` and `build-module` directories getting setup.

Still something wonky here if the provided command in the readme.md doesn't install things as expected (but might be related to there not being a "stable" release yet).  Maybe just a change in the README.md is needed until the stable release?

**Comment by gziolo** [comment]
`v1.0.0` was published today so it is possible to use `npm install @wordpress/dom-ready --save`. I think this resolves this issue. Feel free to re-open if you still encounter some issues.
