### ISSUE TITLE
What's different between hooks(this package) and Event in Node.js?

### ISSUE THREAD

**Issue by Aqours** [WordPress/packages#43]
I found hooks can be applyed on plain object. ([Make WordPress Core](https://core.trac.wordpress.org/ticket/21170))

Event can be also applyed on plain object in Node.js which can be used in browser too.
I don't understand what's different between hooks and Event in Node.js?

link: [Node.js Event API](https://nodejs.org/api/events.html)

**Comment by gziolo** [comment]
> I don't understand what's different between hooks and Event in Node.js?

They use a completely different API. The `@wordpres/hooks` package reimplements WordPress PHP API for actions and filters. See an example method: https://developer.wordpress.org/reference/functions/apply_filters/. Its definition matches between JS and PHP to make it more convenient to switch between those two languages when modifying or extending WordPress capabilities.

It's perfectly fine to use Node.js Event API to achieve the same goal. You just need to learn two 2 APIs when switching between JS and PHP.
