### ISSUE TITLE
Hooks: `hasFilter` and `hasAction` return number, not boolean

### ISSUE THREAD

**Issue by aduth** [WordPress/packages#78]
The naming and inline documentation for `hasFilter` and `hasAction` implies that a boolean value is returned from these functions. However, the implementation reveals that the return value is a number representing the number of handlers present for the hook:

https://github.com/WordPress/packages/blob/47ff850ee682aa539dde839fa3f08445c888d757/packages/hooks/src/createHasHook.js#L20-L22

In typical usage this would be a non-concern, since a general [truthiness](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) condition would have the same result. Strict equality or otherwise relying on a boolean value would fail:

```js
addFilter( 'hookName', 'my-handler', applyHandler );

if ( hasFilter( 'hookName' ) ) {
	// OK
}

if ( hasFilter( 'hookName' ) === true ) {
	// Not OK
}
```

Suggestion is to make one of the following changes: 

- Update `hasHook` to return a boolean value
- Change the function name and inline documentation to reflect that a number is returned

**Comment by adamsilverstein** [comment]
Thanks for raising this issue @aduth - I agree the naming here is confusing. My inclination would be to change the code here to return an actual boolean.

I think the original intent was to match the core function https://developer.wordpress.org/reference/functions/has_filter/ and https://developer.wordpress.org/reference/functions/has_action/ - these function return a boolean (false) if no hook is registered, otherwise they return _the priority of the hook_ which could be useful in php where a matching priority is required to remove a hook.

**Comment by felixarntz** [comment]
In terms of naming I agree the functions should be changed to return a boolean, however it should also remain possible to get the hook priority. Maybe separate functions would be useful, such as `getFilterPriority()` and `getActionPriority()`.

**Comment by aduth** [comment]
Well, even as currently implemented, priority is not returned, rather the number of handlers for a given hook name 😄

**Comment by adamsilverstein** [comment]
> Maybe separate functions would be useful, such as getFilterPriority() and getActionPriority().

I like this suggestion! I'll work on a PR soon.

**Comment by adamsilverstein** [comment]
The issue reported here is resolved with this commit, I'll open a PR: https://github.com/WordPress/packages/commit/e743ff12c9ed29030bed3d4cb7b4f047267eb323

I noticed when looking at this that the core functions support an optional second parameter - the callback name. when this is passed the function checks for the existence of that specific callback registration which would be even more useful. I'll open a new Issues for that and getting the priority which would also require passing the callback name.
